services:
  - type: web
    name: battleship-game
    env: node
    plan: starter
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    domains:
      - battleship-game.onrender.com